// Mocks generated by Mockito 5.0.0-nullsafety.7 from annotations
// in charts_common/test/chart/cartesian/axis/time/basic_date_time_tick_formatter_spec_test.dart.
// Do not manually edit this file.

import 'package:charts_common/src/chart/common/behavior/a11y/a11y_node.dart'
    as _i5;
import 'package:charts_common/src/chart/common/chart_context.dart' as _i4;
import 'package:charts_common/src/common/date_time_factory.dart' as _i3;
import 'package:charts_common/src/common/rtl_spec.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeRTLSpec extends _i1.Fake implements _i2.RTLSpec {}

class _FakeDateTimeFactory extends _i1.Fake implements _i3.DateTimeFactory {}

/// A class which mocks [ChartContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockChartContext extends _i1.Mock implements _i4.ChartContext {
  MockChartContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get chartContainerIsRtl =>
      (super.noSuchMethod(Invocation.getter(#chartContainerIsRtl),
          returnValue: false) as bool);
  @override
  _i2.RTLSpec get rtlSpec => (super.noSuchMethod(Invocation.getter(#rtlSpec),
      returnValue: _FakeRTLSpec()) as _i2.RTLSpec);
  @override
  bool get isRtl =>
      (super.noSuchMethod(Invocation.getter(#isRtl), returnValue: false)
          as bool);
  @override
  bool get isTappable =>
      (super.noSuchMethod(Invocation.getter(#isTappable), returnValue: false)
          as bool);
  @override
  double get pixelsPerDp =>
      (super.noSuchMethod(Invocation.getter(#pixelsPerDp), returnValue: 0.0)
          as double);
  @override
  _i3.DateTimeFactory get dateTimeFactory =>
      (super.noSuchMethod(Invocation.getter(#dateTimeFactory),
          returnValue: _FakeDateTimeFactory()) as _i3.DateTimeFactory);
  @override
  void requestAnimation(Duration? transition) =>
      super.noSuchMethod(Invocation.method(#requestAnimation, [transition]),
          returnValueForMissingStub: null);
  @override
  void enableA11yExploreMode(List<_i5.A11yNode>? nodes,
          {String? announcement}) =>
      super.noSuchMethod(
          Invocation.method(
              #enableA11yExploreMode, [nodes], {#announcement: announcement}),
          returnValueForMissingStub: null);
}
